version: '3.8'
services:

  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oscar
      - MONGO_INITDB_ROOT_PASSWORD=1234

  backend:
    build: ./backend
    ports:
      - "80:80"
    environment:
      - MONGODB_USERNAME=oscar
      - MONGODB_PASSWORD=1234
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

#    env_file:
#      - ./mongo.env

volumes:
  data:
  logs: